export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_REQUEST_SUCCESS = 'ADD_TODO_REQUEST_SUCCESS';
export const ADD_TODO_REQUEST_ERROR = 'ADD_TODO_REQUEST_ERROR';

export const GET_TODO_REQUEST = 'GET_TODO_REQUEST';
export const GET_TODO_REQUEST_SUCCESS = 'GET_TODO_REQUEST_SUCCESS';
export const GET_TODO_REQUEST_ERROR = 'GET_TODO_REQUEST_ERROR';

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_REQUEST_SUCCESS = 'GET_TODOS_REQUEST_SUCCESS';
export const GET_TODOS_REQUEST_ERROR = 'GET_TODOS_REQUEST_ERROR';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_REQUEST_SUCCESS = 'DELETE_TODO_REQUEST_SUCCESS';
export const DELETE_TODO_REQUEST_ERROR = 'DELETE_TODO_REQUEST_ERROR';
