export const GET_WXCONTEXT_REQUEST = 'GET_WXCONTEXT_REQUEST';
export const GET_WXCONTEXT_REQUEST_SUCCESS = 'GET_WXCONTEXT_REQUEST_SUCCESS';
export const GET_WXCONTEXT_REQUEST_ERROR = 'GET_WXCONTEXT_REQUEST_ERROR';
